# Generated by Django 4.1.7 on 2023-05-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_alter_album_release_date_alter_playlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
